version: "3"
services:
  server:
    container_name: ddoring
    image: "limyeonjy/ddoring"
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - app-tier

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - app-tier
    restart: always
    tty: true

networks:
  app-tier:
    driver: bridge
